### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by jwash11** [keethesh/UdemyEnrollEverywhere#6] opened 2020-11-04 14:20 UTC
It stopped working 2 days ago. it's unable to add any courses.(still able to detect courses which you're already enrolled in)

Thanks,

**Comment by keethesh** [comment] 2020-11-04 14:35
Will update whenever I have some time! :)

**Comment by keethesh** [comment] 2020-11-04 14:42
Duplicate of #5
I will update whenever I have some time! :)

**Closed as completed by keethesh** 2020-11-04 14:42 UTC
